[phases.setup]
nixPkgs = ["bun", "unzip"]
aptPkgs = ["build-essential"]

[phases.install]
cmds = ["bun upgrade", "bun install"]

[phases.build]
cmds = ["bun run build"]

[start]
cmd = "bun run start"
